### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/turl_coltype_mlb.pickle'

### ISSUE THREAD

**Issue by simranbhurat** [megagonlabs/doduo#6]
FileNotFoundError: [Errno 2] No such file or directory: './data/turl_coltype_mlb.pickle'

Where can I find this file?

**Comment by kirilltobola** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: './data/turl_coltype_mlb.pickle'
> 
> Where can I find this file?

@simranbhurat, In working directory run script `download.sh`. It will download two archives (data.tar.gz and model.tar.gz) and will decompress them. That missing file will be in "data" directory.

**Comment by simranbhurat** [comment]
Connecting to doduo-data.s3-us-west-2.amazonaws.com (doduo-data.s3-us-west-2.amazonaws.com)|52.92.145.114|:443... **failed: Connection timed out.**

What should I do to avoid Connection timed out warning? I am using WSL and git bash as I am a windows user and download.sh does not seem to work on windows.

**Comment by simranbhurat** [comment]
Just running https://doduo-data.s3-us-west-2.amazonaws.com/data.tar.gz and https://doduo-data.s3-us-west-2.amazonaws.com/model.tar.gz worked. Thank You.
